name: XMobGeneration
version: 1.7
main: com.xmobgeneration.XMobGeneration
api-version: 1.17
depend: [WorldEdit]
softdepend: [MythicMobs]
commands:
  xmg:
    description: Main command for XMobGeneration plugin
    usage: /<command> [subcommand] [args]
    aliases: [xmobgen]
permissions:
      xmg.admin:
        description: Allows access to all XMobGeneration commands
        default: op
      xmg.boss:
        description: Allows access to boss-related commands
        default: op