settings:
  default-mob-type: ZOMBIE
  default-spawn-count: 5
  default-respawn-delay: 30

messages:
  prefix: "&8[&bXMobGeneration&8] &7"
  area-created: "&aSpawn area %name% has been created successfully!"
  area-deleted: "&cSpawn area %name% has been deleted!"
  area-not-found: "&cSpawn area %name% does not exist!"
  area-exists: "&cA spawn area with that name already exists!"
  area-configured: "&aSpawn area %name% has been configured!"
  invalid-mob-type: "&cInvalid mob type specified!"
  invalid-numbers: "&cSpawn count and respawn delay must be greater than 0!"
  no-selection: "&cYou must make a WorldEdit selection first!"
  selection-error: "&cError getting WorldEdit selection!"
  usage-createarea: "&cUsage: /xmg createarea <name>"
  usage-deletearea: "&cUsage: /xmg deletearea <name>"
  usage-configarea: "&cUsage: /xmg configarea <name> <mobType> <spawnCount> <respawnDelay>"
  pos1-set: "&aPosition 1 set!"
  pos2-set: "&aPosition 2 set!"
  max-areas-reached: "&cMaximum number of areas (45) has been reached!"